# Generated by Django 5.2.6 on 2025-11-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_course_options_attendancesession_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='checkin_code',
            field=models.CharField(blank=True, help_text='Optional simple code students can enter to check in', max_length=32, null=True),
        ),
    ]
