# Generated by Django 5.2.6 on 2025-12-15 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_checkin_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_time',
            field=models.TimeField(blank=True, help_text='Time student actually checked in', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Generated from recurring template'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='late_cutoff_minutes',
            field=models.IntegerField(default=15, help_text='Minutes after start time to auto-mark as late'),
        ),
        migrations.CreateModel(
            name='RecurringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First session date')),
                ('end_date', models.DateField(help_text='Last session date')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('day_of_week', models.IntegerField(default=0, help_text='0=Monday, 6=Sunday (for weekly/biweekly)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sessions', to='attendance.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('error_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='attendance.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
